theme: jekyll-theme-midnight
title: Welcome
description: This is the homepage of Florence Lourdes, a Computer Science student at Southern New Hampshire University. I am interested in Machine Learning, and I have interned twice at Nuance Communications!
